global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'github-webhook-observer-node-exporter'
    static_configs:
      - targets: ['github-webhook-observer-node-exporter:9100']

  - job_name: 'github-webhook-observer'
    static_configs:
      - targets: ['github-webhook-observer:8000']

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'  # Alertmanager endpoint
